#!/usr/bin/env bash
# check_dart_file_size.sh — fail CI when any non-generated Dart file exceeds the
# size threshold. Files containing the literal `// dart-line-count-allow`
# escape-hatch comment are skipped; if you add the hatch you must also add a
# tracking issue link nearby explaining the deferred split.
#
# Excludes: gen/ directories, *.g.dart, *.freezed.dart, app/lib/l10n/
# (generated by `flutter gen-l10n`).
#
# Usage: ./scripts/check_dart_file_size.sh [threshold]
#        Default threshold is 1000 lines.

set -euo pipefail

THRESHOLD=${1:-1000}
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
APP_LIB="$ROOT/app/lib"

if [ ! -d "$APP_LIB" ]; then
  echo "error: $APP_LIB does not exist" >&2
  exit 2
fi

failed=0
while IFS= read -r -d '' file; do
  case "$file" in
    */gen/*|*.g.dart|*.freezed.dart) continue ;;
    */l10n/app_localizations*.dart) continue ;;
  esac
  if grep -q '// dart-line-count-allow' "$file"; then
    continue
  fi
  lines=$(wc -l < "$file")
  if [ "$lines" -gt "$THRESHOLD" ]; then
    rel="${file#"$ROOT/"}"
    echo "FAIL: $rel has $lines lines (limit $THRESHOLD)"
    failed=1
  fi
done < <(find "$APP_LIB" -name '*.dart' -print0)

if [ "$failed" -ne 0 ]; then
  echo
  echo "Some non-generated Dart files exceed $THRESHOLD lines."
  echo "Either split the file or, if a split is genuinely deferred, add the"
  echo "comment '// dart-line-count-allow' near the top of the file with a"
  echo "tracking-issue reference explaining why."
  exit 1
fi

echo "All non-generated Dart files are <= $THRESHOLD lines."
