#!/usr/bin/env bash
# Disable the Dart VM profiler for `flutter test` on this machine by replacing
# the flutter_tester engine artifact with a shim that drops
# --enable-dart-profiling from the argument list flutter_tools passes it.
#
# TODO(#2933): Delete this script and its call sites in
# .github/workflows/test_flutter.yaml and scripts/runner_candidate_checks.sh once
# a Flutter release ships a fixed Dart VM profiler stack walker. Flutter 3.47.0
# (Dart 3.13.0) segfaults flutter_tester at roughly 0.2% of process starts: the
# profiler samples by signalling the thread, and a sample landing on code built
# without a frame pointer seeds the native stack walker with a non-frame pointer.
# The walker validates only "increasing" and "below the stack ceiling", so it
# follows that seed into the heap and dereferences an unmapped page — inside the
# signal handler, so the process dies. flutter_tools blames whichever test file
# that tester owned, which reads as a random regression in unrelated code. The
# blocker for a cleaner fix is that `flutter test` builds DebuggingOptions with
# enableDartProfiling defaulting to true and exposes no flag to change it, so the
# artifact is the only interception point. Removal criterion: re-run the suite on
# the newer Flutter without this shim and confirm it is crash-free.
#
# Behaviour-neutral for test runs: flutter_tools also passes --disable-vm-service,
# so nothing ever reads the samples the profiler collects.

set -euo pipefail

readonly MARKER='ripls-2933-flutter-tester-shim'

sdk_root=""
if [ -n "${FLUTTER_ROOT:-}" ]; then
  sdk_root="$FLUTTER_ROOT"
elif flutter_bin=$(command -v flutter 2>/dev/null); then
  if resolved=$(readlink -f "$flutter_bin" 2>/dev/null); then
    flutter_bin="$resolved"
  fi
  sdk_root=$(cd "$(dirname "$flutter_bin")/.." && pwd)
fi

if [ -z "$sdk_root" ] || [ ! -d "$sdk_root" ]; then
  echo "error: cannot locate the Flutter SDK; set FLUTTER_ROOT or put flutter on PATH" >&2
  exit 1
fi

shopt -s nullglob
testers=("$sdk_root"/bin/cache/artifacts/engine/*/flutter_tester)
shopt -u nullglob

if [ ${#testers[@]} -eq 0 ]; then
  echo "error: no flutter_tester artifact under $sdk_root/bin/cache/artifacts/engine" >&2
  echo "       (run 'flutter precache' first so the engine artifacts exist)" >&2
  exit 1
fi

for tester in "${testers[@]}"; do
  dir=$(dirname "$tester")
  real="$dir/flutter_tester.real"

  if grep -q "$MARKER" "$tester" 2>/dev/null; then
    # Already shimmed by an earlier run; the real binary must still be beside it.
    if [ ! -x "$real" ]; then
      echo "error: $tester is a shim but $real is missing" >&2
      echo "       restore the artifact with 'flutter precache --force' and re-run" >&2
      exit 1
    fi
  else
    mv "$tester" "$real"
  fi

  # Write to a sibling temp file and rename, so an interrupted run can never
  # leave the SDK without a flutter_tester.
  tmp="$dir/.flutter_tester.shim.$$"
  cat > "$tmp" <<SHIM
#!/bin/bash
# $MARKER — generated by scripts/disable_flutter_tester_profiler.sh (TODO(#2933))
args=()
for arg in "\$@"; do
  case "\$arg" in
    --enable-dart-profiling) continue ;;
    *) args+=("\$arg") ;;
  esac
done
exec "$real" "\${args[@]}"
SHIM
  chmod +x "$tmp"
  mv "$tmp" "$tester"

  echo "Dart profiler disabled for $tester (#2933)"
done

if [ -n "${GITHUB_ACTIONS:-}" ]; then
  echo "::notice::flutter_tester is running with the Dart profiler disabled (#2933 workaround)"
fi
