package ai

import (
	"context"
	"testing"
)

// TestExperienceGeneration_TimeExtraction verifies that the experience generation
// includes time extraction fields in the response.
func TestExperienceGeneration_TimeExtraction(t *testing.T) {
	tests := []struct {
		name               string
		prompt             string
		currentTime        string
		expectedDate       string // Expected date in YYYY-MM-DD format (empty if no date expected)
		expectedTime       string // Expected time in HH:MM format (empty if no time expected)
		expectedConfidence string // EXPLICIT, INFERRED, or UNKNOWN
	}{
		{
			name:               "explicit time - tomorrow morning",
			prompt:             "hiking tomorrow morning",
			currentTime:        "2025-11-30T15:00:00-07:00",
			expectedDate:       "2025-12-01",
			expectedTime:       "08:00",
			expectedConfidence: "INFERRED",
		},
		{
			name:               "explicit time - specific time",
			prompt:             "board game night friday 7pm",
			currentTime:        "2025-11-30T15:00:00-07:00",
			expectedDate:       "2025-12-05",
			expectedTime:       "19:00",
			expectedConfidence: "EXPLICIT",
		},
		{
			name:               "no time mentioned",
			prompt:             "coffee sometime",
			currentTime:        "2025-11-30T15:00:00-07:00",
			expectedDate:       "",
			expectedTime:       "",
			expectedConfidence: "UNKNOWN",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// Use mock provider which returns predictable results
			provider := NewMockProvider()

			// Override the mock function to return controlled data
			provider.GenerateExperienceFromTextFunc = func(ctx context.Context, prompt, region, currentTime string) (*ExperienceGeneration, error) {
				// Verify currentTime is passed correctly
				if currentTime != tt.currentTime {
					t.Errorf("currentTime = %v, want %v", currentTime, tt.currentTime)
				}

				// Return a response with time fields populated
				return &ExperienceGeneration{
					Title:          "Test Experience",
					Description:    "Test description",
					Confidence:     0.9,
					SearchKeywords: []string{"test"},
					Date:           tt.expectedDate,
					Time:           tt.expectedTime,
					TimeConfidence: tt.expectedConfidence,
				}, nil
			}

			ctx := context.Background()
			result, err := provider.GenerateExperienceFromText(ctx, tt.prompt, "Test Region", tt.currentTime)
			if err != nil {
				t.Fatalf("GenerateExperienceFromText() error = %v", err)
			}

			// Verify time extraction fields are present
			if result.Date != tt.expectedDate {
				t.Errorf("Date = %v, want %v", result.Date, tt.expectedDate)
			}
			if result.Time != tt.expectedTime {
				t.Errorf("Time = %v, want %v", result.Time, tt.expectedTime)
			}
			if result.TimeConfidence != tt.expectedConfidence {
				t.Errorf("TimeConfidence = %v, want %v", result.TimeConfidence, tt.expectedConfidence)
			}
		})
	}
}

// TestExperienceGeneration_RequiredFields verifies that the new time fields
// don't break existing functionality.
func TestExperienceGeneration_RequiredFields(t *testing.T) {
	provider := NewMockProvider()
	ctx := context.Background()

	result, err := provider.GenerateExperienceFromText(ctx, "test prompt", "Test Region", "2025-11-30T15:00:00-07:00")
	if err != nil {
		t.Fatalf("GenerateExperienceFromText() error = %v", err)
	}

	// Verify original fields still work
	if result.Title == "" {
		t.Error("Title should not be empty")
	}
	// Description is no longer generated by providers in text mode;
	// the service layer sets it to the user's original text.
	if result.Confidence == 0 {
		t.Error("Confidence should not be zero")
	}

	// Verify new fields exist (they can be empty for backward compatibility)
	// Just check they're accessible without panicking
	_ = result.Date
	_ = result.Time
	_ = result.TimeConfidence
}
